# Site settings
title: Felipe Sabino
email: felipesabino-experiments@sabino.me
author: Felipe Sabino
description: "My stuf..."
baseurl: ""
url: "http://felipesabino-experiments.github.io/pixyll"
google_analytics:

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
